### ISSUE TITLE
favicon과 apple-touch-icon의 리소스가 존재하지 않습니다.

### ISSUE THREAD

**Issue by jthcast** [planetarium/snack.planetarium.dev#131]
안녕하세요, 정태훈입니다.

기술 블로그를 둘러보던 중 favicon과 apple-touch-icon의 리소스가 존재하지 않음을 발견했습니다.

**Comment by riemannulus** [comment]
안녕하세요. 제보 감사합니다!
빠른 시일 내로 추가하도록 하겠습니다 :)
