### ISSUE TITLE
포스트에 첨부한 이미지가 보이지 않습니다

### ISSUE THREAD

**Issue by mu-hun** [planetarium/snack.planetarium.dev#186]
> <img width="567" alt="스크린샷 2024-05-11 오후 2 36 30" src="https://github.com/planetarium/snack.planetarium.dev/assets/5278201/b73addb7-712c-478b-beb5-21b5b4308ffa">
> 
> [Unity DOTS DynamicBuffer 사용하기](https://snack.planetarium.dev/kor/2020/05/unity-dots-start-to-use-dynamic-buffer/)

로컬에서 직접 빌드해서 확인해보니 개별 포스트마다 갖고 있는 이미지 에셋 경로 `posts/*/*/images`가 빌드 타겟에 누락이 되고 있습니다. 

많지는 않은 개수인데 총 3개 포스트가 이미지를 첨부하고 있네요:

- https://snack.planetarium.dev/kor/2020/05/unity-dots-start-to-use-dynamic-buffer/
- https://snack.planetarium.dev/kor/2020/06/junior-experience/
- https://snack.planetarium.dev/kor/2020/10/decentralized-and-online-game-intersect/

<img width="720" alt="스크린샷 2024-05-11 오후 2 13 58" src="https://github.com/planetarium/snack.planetarium.dev/assets/5278201/68cdfe63-c244-4de3-b2fe-861b20b90788">

[가장 최근 웹 아카이브 이력인 1월 24일자](https://web.archive.org/web/20240224180558/https://snack.planetarium.dev/kor/)에는 이미지가 잘 임베딩되어 있어서 hugo 버전을 올린 이후 #185 에 발생하는 것 같습니다. 확인 부탁드립니다.

**Comment by boscohyun** [comment]
안녕하세요 @mu-hun 님! 친절한 설명과 함께 이슈 만들어주신 점 감사드립니다.🙂

**Comment by riemannulus** [comment]
감사합니다! 확인 후 고쳐두겠습니다.

**Comment by mu-hun** [comment]
블로그 퍼머링크를 방문할 일이 있어서 오랜만에 다시 디버깅해보니 `index.md` 파일을 넣으니 해결되네요..

몇가지 테스트를 거쳐보니 바꾸신 Hugo 버전 0.88 -> 0.123 사이에 포스트 내부 에셋 (ex `content/posts/*/**/<post-name>/*/*.{png,css,..etc}`) 포함 알고리즘이 멀티렝귀지 마크다운 문서 추적과 별개로 메인 문서 `index.md` 유무로 작동하게 바뀐 것 같습니다.

 Hugo 측 버그라는 이야기입니다.  #188 마침 새 포스트를 준비 중이신 걸로 보이는데 도움이 되셨으면 좋겠습니다.

**Comment by mu-hun** [comment]
혹시 이번에 다시 Hugo를 최근 버전으로 올리시게 되신다면 반려된 변경 사항이 아나 있어 제가 디버깅 과정에 기록한 이력도 도움이 되셨으면 좋겠습니다:

https://github.com/mu-hun/snack.planetarium.dev/pull/2

괜찮으시면 기존 포스트 빈 `index.md` 생성 작업까지 새 PR로 올려드릴 수도 있습니다.

**Comment by mu-hun** [comment]
직접 제보해보니 https://github.com/gohugoio/hugo/issues/11453 이 자료를 참고하라고 답변을 받았는데요, 문제 해결하실 때 참고하면 될 것 같습니다.

**Comment by mu-hun** [comment]
개인 포트폴리오 정리 중에 다시 이 이슈를 보게 되었는데요, 괜찮으시면 제가 기존 포스트에 대한 복구 작업만 도와드리고 싶은 의향이 있습니다.

위에 안내된 링크에 따르면 포스트 디렉토리 구조 및 페이지 경로 구성이 크게 달라지게 되는데요, 현재 구성을 유지하되 기존 포스트 이미지를 보여드리고자 하신다면 이미지가 들여 있는 포스트마다 빈 `index.md` 파일을 추가드리고 싶습니다.

**Comment by boscohyun** [comment]
@mu-hun 저희가 아직 살피지 못한 부분인데 기꺼이 기여해주신다니 감사합니다.👍

**Comment by moreal** [comment]
안녕하세요 @mu-hun 님, 이 이슈와 관련해서 직접 디버깅하며 조사해주셔서 정말 감사합니다 🙇🏻 PR #191 에서 조사해주신 내용을 통해 이미지가 보이지 않는 문제가 해결될 수 있었습니다. 무훈님이 이전에 작성해주셨던 글들도 이제는 이미지가 잘 보이는 듯 합니다!

- https://snack.planetarium.dev/kor/2020/06/junior-experience/
- https://snack.planetarium.dev/kor/2020/10/decentralized-and-online-game-intersect/

그리고 앞서 승민님이 달아주신 코멘트를 확인하지 못하고 PR을 올려버려서, 무훈님도 PR을 준비 중 이시지는 않았을까 싶어 사과의 말씀도 드립니다 😞 

다시금 기여해주셔서 감사합니다 🙇🏻‍♂️

**Comment by eugene-doobu** [comment]
안녕하세요, 해당 pr적용 이후 윈도우에서 hugo server 셋팅시 사이트 빌딩에 실패하고 있습니다.
https://github.com/planetarium/snack.planetarium.dev/pull/191
해당 pr이 머지되기 이전 커밋인 578f803c017315df3ed65cc1b87bee8759e65620에서까지 정상 동작 확인은 되었습니다.
최신 main브랜치 기준으로 발생하는 에러 공유드립니다.
```
PS C:\Users\ssund\Documents\GitHub\snack.planetarium.dev> hugo server -w -F
Watching for changes in C:\Users\ssund\Documents\GitHub\snack.planetarium.dev\{archetypes,content,data,layouts,static,themes}
Watching for config changes in C:\Users\ssund\Documents\GitHub\snack.planetarium.dev\config.toml
Start building sites …
hugo v0.123.8-5fed9c591b694f314e5939548e11cc3dcb79a79c+extended windows/amd64 BuildDate=2024-03-07T13:14:42Z VendorInfo=gohugoio

Built in 50 ms
Error: error building site: render: failed to render pages: render of "home" failed: "C:\Users\ssund\Documents\GitHub\snack.planetarium.dev\themes\hugo-planetarium\layouts\index.html:1:12": execute of template failed: template: index.html:1:12: executing "index.html" at <hugo>: can't evaluate field IsMultilingual in type interface {}
```

**Comment by moreal** [comment]
위 코멘트에 대해서는 로컬 hugo 버전의 문제로 보여 슬랙에서 따로 말씀드렸습니다.

**Comment by eugene-doobu** [comment]
> 위 코멘트에 대해서는 로컬 hugo 버전의 문제로 보여 슬랙에서 따로 말씀드렸습니다.

hugo버전 업데이트 후 정상 동작 확인해서 코멘트 수정해두었습니다 감사합니다 ( _ _ )

**Comment by mu-hun** [comment]
문제 다 해결되셨으면 이슈 닫아주세요!
